import { Shape, ShapeType, MachineSettings } from '../types';

export const generateGCode = (shapes: Shape[], settings: MachineSettings): string => {
  const { feedRate, safeHeight, cutDepth } = settings;
  const lines: string[] = [];

  // Header
  lines.push('; Generated by CNC Forge AI');
  lines.push('G21 ; Metric units');
  lines.push('G90 ; Absolute positioning');
  lines.push(`G0 Z${safeHeight} ; Move to safe height`);
  lines.push('M3 S1000 ; Spindle on');

  shapes.forEach((shape) => {
    lines.push(`; Shape: ${shape.type} (ID: ${shape.id})`);
    
    switch (shape.type) {
      case ShapeType.RECTANGLE:
        // Move to start corner
        lines.push(`G0 X${shape.x} Y${shape.y}`);
        // Plunge
        lines.push(`G1 Z${-cutDepth} F${feedRate / 2}`);
        // Cut rectangle
        lines.push(`G1 X${shape.x + shape.width} Y${shape.y} F${feedRate}`);
        lines.push(`G1 X${shape.x + shape.width} Y${shape.y + shape.height}`);
        lines.push(`G1 X${shape.x} Y${shape.y + shape.height}`);
        lines.push(`G1 X${shape.x} Y${shape.y}`);
        // Retract
        lines.push(`G0 Z${safeHeight}`);
        break;

      case ShapeType.CIRCLE:
        // Move to start point (rightmost point of circle)
        lines.push(`G0 X${shape.x + shape.radius} Y${shape.y}`);
        // Plunge
        lines.push(`G1 Z${-cutDepth} F${feedRate / 2}`);
        // Cut circle (Clockwise)
        // I and J are relative offsets to the center from current position
        // Current: (x+r, y). Center: (x, y). Offset: (-r, 0)
        lines.push(`G2 X${shape.x + shape.radius} Y${shape.y} I-${shape.radius} J0 F${feedRate}`);
        // Retract
        lines.push(`G0 Z${safeHeight}`);
        break;

      case ShapeType.TEXT:
        lines.push(`; Text engraving not fully implemented for font paths`);
        lines.push(`; Text: "${shape.text}" at ${shape.x},${shape.y}`);
        // Placeholder box for text
        const estimatedWidth = shape.text.length * (shape.fontSize * 0.6);
        lines.push(`G0 X${shape.x} Y${shape.y}`);
        lines.push(`G1 Z${-cutDepth} F${feedRate / 2}`);
        lines.push(`G1 X${shape.x + estimatedWidth} Y${shape.y} F${feedRate}`);
        lines.push(`G0 Z${safeHeight}`);
        break;
    }
    lines.push('');
  });

  // Footer
  lines.push('M5 ; Spindle off');
  lines.push('G0 X0 Y0 ; Return home');
  lines.push('M30 ; End program');

  return lines.join('\n');
};
